# Generated by Django 5.2.17 on 2026-09-27 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("projects", "0002_submission_submissionversion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="events.track",
            ),
        ),
    ]
