# Generated by Django 5.2.17 on 2026-09-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_mentornote"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="gallery_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="gallery_visible",
            field=models.BooleanField(default=True),
        ),
    ]
