from django.urls import path

from . import judge_directory, judge_expertise, views

_EVENT = "workspaces/<uuid:workspace_public_id>/events/<uuid:event_public_id>"
_STAGE = f"{_EVENT}/stages/<uuid:stage_public_id>"
_POOL = f"{_EVENT}/evaluation-pools/<uuid:pool_public_id>"
_PLAN = f"{_STAGE}/evaluation-plans/<uuid:plan_public_id>"

urlpatterns = [
    path(
        "workspaces/<uuid:workspace_public_id>/my-judge-expertise/",
        judge_expertise.JudgeExpertiseView.as_view(),
        name="my-judge-expertise",
    ),
    path(
        "workspaces/<uuid:workspace_public_id>/judge-expertise/<uuid:judge_public_id>/",
        judge_expertise.JudgeExpertiseView.as_view(),
        name="judge-expertise",
    ),
    path(
        "workspaces/<uuid:workspace_public_id>/judge-directory/",
        judge_directory.JudgeDirectoryView.as_view(),
        name="judge-directory",
    ),
    path(
        "workspaces/<uuid:workspace_public_id>/my-judge-invitations/",
        judge_directory.MyJudgeInvitationView.as_view(),
        name="my-judge-invitations",
    ),
    path(
        "workspaces/<uuid:workspace_public_id>/my-judge-invitations/<uuid:invitation_public_id>/respond/",
        judge_directory.JudgeInvitationDetailView.as_view(),
        name="judge-invitation-respond",
    ),
    path(
        f"{_EVENT}/judge-invitations/",
        judge_directory.JudgeInvitationListView.as_view(),
        name="judge-invitation-list",
    ),
    path(
        f"{_EVENT}/judge-invitations/<uuid:invitation_public_id>/",
        judge_directory.JudgeInvitationRevokeView.as_view(),
        name="judge-invitation-revoke",
    ),
    path(
        f"{_EVENT}/workflow-presets/",
        views.WorkflowPresetListView.as_view(),
        name="workflow-preset-list",
    ),
    path(
        f"{_EVENT}/workflow-presets/apply/",
        views.WorkflowPresetApplyView.as_view(),
        name="workflow-preset-apply",
    ),
    path(
        f"{_EVENT}/judge-calendar/",
        views.JudgeCalendarView.as_view(),
        name="judge-calendar",
    ),
    path(
        f"{_EVENT}/judge-workload/",
        views.JudgeWorkloadView.as_view(),
        name="judge-workload",
    ),
    path(
        f"{_STAGE}/evaluation-plans/",
        views.EvaluationPlanListView.as_view(),
        name="evaluation-plan-list",
    ),
    path(f"{_PLAN}/", views.EvaluationPlanDetailView.as_view(), name="evaluation-plan-detail"),
    path(
        f"{_PLAN}/publish-rubric/",
        views.RubricPublishView.as_view(),
        name="evaluation-plan-publish-rubric",
    ),
    path(f"{_PLAN}/ballots/", views.BallotListCreateView.as_view(), name="evaluation-plan-ballots"),
    path(
        f"{_PLAN}/candidates/",
        views.CandidateListView.as_view(),
        name="evaluation-plan-candidates",
    ),
    path(
        f"{_PLAN}/assignments/activate/",
        views.AssignmentActivateView.as_view(),
        name="evaluation-plan-assignments-activate",
    ),
    path(
        f"{_PLAN}/assignments/preview/",
        views.AssignmentPreviewView.as_view(),
        name="evaluation-plan-assignments-preview",
    ),
    path(
        f"{_PLAN}/assignments/rebalance/",
        views.AssignmentRebalanceView.as_view(),
        name="evaluation-plan-assignments-rebalance",
    ),
    path(
        f"{_PLAN}/assignments/dropout-simulation/",
        views.AssignmentDropoutSimulationView.as_view(),
        name="evaluation-plan-assignments-dropout-simulation",
    ),
    path(
        f"{_PLAN}/assignments/compare/",
        views.AssignmentCompareView.as_view(),
        name="evaluation-plan-assignments-compare",
    ),
    path(
        f"{_PLAN}/assignments/activate-optimized/",
        views.AssignmentActivateOptimizedView.as_view(),
        name="evaluation-plan-assignments-activate-optimized",
    ),
    path(
        f"{_PLAN}/assignments/",
        views.AssignmentDetailView.as_view(),
        name="evaluation-plan-assignments",
    ),
    path(
        f"{_EVENT}/evaluation-pools/",
        views.EvaluationPoolListView.as_view(),
        name="evaluation-pool-list",
    ),
    path(
        f"{_POOL}/memberships/",
        views.PoolMembershipListView.as_view(),
        name="pool-membership-list",
    ),
    path(
        f"{_POOL}/memberships/<uuid:membership_public_id>/",
        views.PoolMembershipDetailView.as_view(),
        name="pool-membership-detail",
    ),
    path(
        f"{_EVENT}/judge-conflicts/",
        views.ConflictOfInterestListCreateView.as_view(),
        name="judge-conflict-list",
    ),
    path(
        f"{_EVENT}/coi-relationships/",
        views.JudgeCOIRelationshipView.as_view(),
        name="coi-relationships",
    ),
    path(
        f"{_EVENT}/coi-relationships/<uuid:relationship_public_id>/",
        views.JudgeCOIRelationshipDetailView.as_view(),
        name="coi-relationship-detail",
    ),
    path(
        f"{_EVENT}/coi-project-attributes/",
        views.ProjectCOIAttributeView.as_view(),
        name="coi-project-attributes",
    ),
    path(
        f"{_EVENT}/coi-project-attributes/<uuid:attribute_public_id>/",
        views.ProjectCOIAttributeDetailView.as_view(),
        name="coi-project-attribute-detail",
    ),
    path(f"{_EVENT}/coi-rules/", views.COIRuleView.as_view(), name="coi-rules"),
    path(
        f"{_PLAN}/normalization-runs/",
        views.NormalizationRunListView.as_view(),
        name="evaluation-plan-normalization-runs",
    ),
    path(
        f"{_PLAN}/ballots/<uuid:project_public_id>/draft/",
        views.BallotDraftView.as_view(),
        name="evaluation-plan-ballot-draft",
    ),
    path(
        f"{_PLAN}/progress/",
        views.EvaluationProgressView.as_view(),
        name="evaluation-plan-progress",
    ),
    path(
        f"{_PLAN}/publish-results/",
        views.ResultsPublishView.as_view(),
        name="evaluation-plan-publish-results",
    ),
    path(
        f"{_PLAN}/close-calls/",
        views.CloseCallsView.as_view(),
        name="evaluation-plan-close-calls",
    ),
    path(
        f"{_PLAN}/sensitivity/",
        views.SensitivityExplorerView.as_view(),
        name="evaluation-plan-sensitivity",
    ),
    path(
        f"{_PLAN}/rubric-lab/",
        views.RubricLabView.as_view(),
        name="evaluation-plan-rubric-lab",
    ),
    path(f"{_PLAN}/results/", views.ResultsView.as_view(), name="evaluation-plan-results"),
    path(
        f"{_PLAN}/provenance/<uuid:project_public_id>/",
        views.JudgingProvenanceView.as_view(),
        name="evaluation-plan-provenance",
    ),
    path(
        f"{_PLAN}/results.csv",
        views.ResultsCsvExportView.as_view(),
        name="evaluation-plan-results-csv",
    ),
    path(
        f"{_PLAN}/feedback/<uuid:project_public_id>/",
        views.ProjectFeedbackView.as_view(),
        name="evaluation-plan-feedback",
    ),
    path(
        f"{_PLAN}/pairwise/next/",
        views.PairwiseNextPairView.as_view(),
        name="evaluation-plan-pairwise-next",
    ),
    path(
        f"{_PLAN}/pairwise/comparisons/",
        views.PairwiseComparisonListCreateView.as_view(),
        name="evaluation-plan-pairwise-comparisons",
    ),
    path(
        f"{_PLAN}/pairwise/runs/",
        views.PairwiseRunListView.as_view(),
        name="evaluation-plan-pairwise-runs",
    ),
    path(
        f"{_PLAN}/pairwise/publish-results/",
        views.PairwiseResultsPublishView.as_view(),
        name="evaluation-plan-pairwise-publish-results",
    ),
    path(
        f"{_PLAN}/pairwise/results/",
        views.PairwiseResultsView.as_view(),
        name="evaluation-plan-pairwise-results",
    ),
    path(
        f"{_PLAN}/pairwise/results.csv",
        views.PairwiseResultsCsvExportView.as_view(),
        name="evaluation-plan-pairwise-results-csv",
    ),
    path(
        f"{_PLAN}/calibration-projects/",
        views.CalibrationProjectsView.as_view(),
        name="evaluation-plan-calibration-projects",
    ),
    path(
        f"{_PLAN}/calibration/ballots/",
        views.CalibrationBallotListCreateView.as_view(),
        name="evaluation-plan-calibration-ballots",
    ),
    path(
        f"{_PLAN}/calibration/status/",
        views.CalibrationStatusView.as_view(),
        name="evaluation-plan-calibration-status",
    ),
    path(
        f"{_PLAN}/calibration/summary/",
        views.CalibrationSummaryView.as_view(),
        name="evaluation-plan-calibration-summary",
    ),
    path(
        f"{_PLAN}/agreement/",
        views.AgreementSummaryView.as_view(),
        name="evaluation-plan-agreement",
    ),
]
