# Generated by Django 5.2.17 on 2026-09-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("participation", "0003_teamopening_marketplaceprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceprofile",
            name="availability_hours_per_week",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketplaceprofile",
            name="interests",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="marketplaceprofile",
            name="roles",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="teamopening",
            name="desired_roles",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="teamopening",
            name="interests",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="teamopening",
            name="min_availability_hours_per_week",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
