# Generated by Django 5.2.17 on 2026-09-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("participant", "Participant"),
                    ("judge", "Judge"),
                    ("organizer", "Organizer"),
                    ("admin", "Admin"),
                    ("mentor", "Mentor"),
                    ("volunteer", "Volunteer"),
                    ("sponsor", "Sponsor"),
                ],
                max_length=20,
            ),
        ),
    ]
