# Generated by Django 5.2.17 on 2026-09-28 21:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_login_failure"),
    ]

    operations = [
        migrations.CreateModel(
            name="OidcLoginState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("state_hash", models.CharField(max_length=64, unique=True)),
                ("browser_hash", models.CharField(max_length=64)),
                ("nonce", models.CharField(max_length=64)),
                ("code_verifier", models.CharField(max_length=128)),
                ("next_path", models.CharField(default="/", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("issuer", models.CharField(max_length=300)),
                ("subject", models.CharField(max_length=255)),
                ("email", models.CharField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("issuer", "subject"), name="unique_external_identity"
                    )
                ],
            },
        ),
    ]
