# Generated by Django 5.2.17 on 2026-09-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="interests",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_roles",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
