# Generated by Django 5.2.17 on 2026-09-26 23:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporalGate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("opens_at", models.DateTimeField(blank=True, null=True)),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporal_gates",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("event", "name"), name="unique_gate_name_event")
                ],
            },
        ),
    ]
