# Generated by Django 5.2.17 on 2026-09-26 23:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("policies", "0002_temporalgate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExceptionGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "Submit"),
                            ("join", "Join"),
                            ("advance", "Advance"),
                            ("vote", "Vote"),
                            ("award", "Award"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject_type", models.CharField(max_length=100)),
                ("subject_id", models.CharField(max_length=64)),
                ("scope", models.CharField(blank=True, default="", max_length=120)),
                ("reason", models.TextField(blank=True, default="")),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exception_grants",
                        to="events.event",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
