# Generated by Django 5.2.17 on 2026-09-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="participation_mode",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("team_formation", "Team formation"),
                    ("team_locked", "Team locked"),
                ],
                default="team_formation",
                max_length=20,
            ),
        ),
    ]
