# Generated by Django 5.2.17 on 2026-09-27 06:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("evaluations", "0004_evaluationplan_published_normalization_run_and_more"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("require_finalized_submission", models.BooleanField(default=True)),
                (
                    "selection_source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("evaluation", "Evaluation results"),
                            ("community", "Community vote"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("winner_count", models.PositiveSmallIntegerField(default=1)),
                ("allow_stacking", models.BooleanField(default=True)),
                ("conflict_group", models.CharField(blank=True, max_length=80)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "eligibility_track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="awards",
                        to="events.track",
                    ),
                ),
                (
                    "evaluation_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="evaluations.evaluationplan",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrizePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "award",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prize_package",
                        to="awards.award",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PrizeComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("credit", "Credit"),
                            ("discount", "Discount"),
                            ("subscription", "Subscription"),
                            ("hardware", "Hardware"),
                            ("travel", "Travel"),
                            ("service", "Service"),
                            ("mentorship", "Mentorship"),
                            ("swag", "Swag"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="awards.prizepackage",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="award",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="unique_award_name_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="award",
            constraint=models.CheckConstraint(
                condition=models.Q(("winner_count__gte", 1)), name="award_winner_count_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="prizecomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)), name="prize_quantity_positive"
            ),
        ),
    ]
