# Generated by Django 5.2.17 on 2026-09-27 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("awards", "0003_prizefulfillment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="sponsor_contacts",
            field=models.ManyToManyField(
                blank=True, related_name="sponsored_awards", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
