# Generated by Django 5.2.17 on 2026-09-27 15:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0001_initial"),
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deadline", "Submission deadline"),
                            ("judging", "Judging"),
                            ("voting", "Voting"),
                        ],
                        max_length=12,
                    ),
                ),
                ("due_at", models.DateTimeField()),
                ("audience_kind", models.CharField(max_length=40)),
                ("audience_params", models.JSONField(blank=True, default=dict)),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("retry_after", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="events.event",
                    ),
                ),
                (
                    "sent_message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminder",
                        to="communications.message",
                    ),
                ),
            ],
            options={
                "ordering": ["due_at", "id"],
            },
        ),
    ]
