# Generated by Django 5.2.17 on 2026-09-28 03:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0003_bulkreceipt"),
        ("events", "0004_announcement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("kind", models.CharField(max_length=16)),
                ("source_key", models.CharField(max_length=64)),
                ("evidence_digest", models.CharField(max_length=64)),
                ("evidence", models.JSONField()),
                ("disposition", models.CharField(max_length=16)),
                ("note", models.CharField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_reviews",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event", "kind", "source_key", "created_at"],
                        name="communicati_event_i_586a5e_idx",
                    )
                ],
            },
        ),
    ]
