# Generated by Django 5.2.17 on 2026-09-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="hidden_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
