# Generated by Django 5.2.17 on 2026-09-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presentation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageblock",
            name="kind",
            field=models.CharField(
                choices=[
                    ("hero", "Hero"),
                    ("tracks", "Tracks"),
                    ("prizes", "Prizes"),
                    ("schedule", "Schedule"),
                    ("sponsors", "Sponsors"),
                    ("faq", "FAQ"),
                    ("resources", "Resources"),
                    ("gallery", "Gallery"),
                    ("results", "Results"),
                    ("announcements", "Announcements"),
                    ("rich_text", "Rich text"),
                    ("cta", "Call to action"),
                ],
                max_length=20,
            ),
        ),
    ]
