# Generated by Django 5.2.17 on 2026-09-28 04:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_announcement_hidden_at_announcement_version"),
        ("presentation", "0002_alter_pageblock_kind"),
        ("projects", "0004_mentornote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSearchTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tag", models.SlugField(max_length=30)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_tags",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["tag"],
                "indexes": [
                    models.Index(fields=["tag", "project"], name="presentatio_tag_1f8c89_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "tag"), name="unique_project_search_tag"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedPublicSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("filters", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to="events.event",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "owner", "name"), name="unique_owner_event_search_name"
                    )
                ],
            },
        ),
    ]
