# Generated by Django 5.2.17 on 2026-09-28 04:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_announcement_hidden_at_announcement_version"),
        ("presentation", "0003_projectsearchtag_savedpublicsearch"),
        ("stages", "0002_stage_participation_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "surface",
                    models.CharField(
                        choices=[
                            ("gallery", "Gallery"),
                            ("finalists", "Finalists"),
                            ("feedback", "Participant feedback"),
                            ("winners", "Winners"),
                            ("archive", "Archived public event"),
                        ],
                        max_length=12,
                    ),
                ),
                ("opens_at", models.DateTimeField()),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_schedules",
                        to="events.event",
                    ),
                ),
                (
                    "finalist_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stages.stage",
                    ),
                ),
            ],
            options={
                "ordering": ["surface"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "surface"), name="unique_event_publication"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("closes_at__isnull", True),
                            ("closes_at__gt", models.F("opens_at")),
                            _connector="OR",
                        ),
                        name="publication_window_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("finalist_stage__isnull", False), ("surface", "finalists")),
                            models.Q(
                                models.Q(("surface", "finalists"), _negated=True),
                                ("finalist_stage__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="publication_finalist_stage",
                    ),
                ],
            },
        ),
    ]
