# Generated by Django 5.2.17 on 2026-09-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presentation", "0004_publicationschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="theme_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
