# Generated by Django 5.2.17 on 2026-09-28 07:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0005_announcement_hidden_at_announcement_version"),
        ("projects", "0004_mentornote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EligibilityReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("needs_remediation", "Needs remediation"),
                            ("cleared", "Cleared"),
                            ("ineligible", "Ineligible"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("decision_note", models.CharField(blank=True, max_length=1000)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_review",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EligibilityRules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("min_team_size", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_team_size", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("required_artifact_kinds", models.JSONField(blank=True, default=list)),
                ("require_finalized_submission", models.BooleanField(default=False)),
                ("require_track", models.BooleanField(default=False)),
                ("require_clearance", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_rules",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EligibilityFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("code", models.CharField(max_length=60)),
                ("automated", models.BooleanField(default=False)),
                (
                    "severity",
                    models.CharField(
                        choices=[("blocking", "Blocking"), ("advisory", "Advisory")], max_length=10
                    ),
                ),
                ("message", models.CharField(max_length=500)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("addressed", "Addressed by participant"),
                            ("resolved", "Resolved"),
                            ("waived", "Waived"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("participant_response", models.CharField(blank=True, max_length=1000)),
                ("resolution_note", models.CharField(blank=True, max_length=500)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("addressed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="eligibility.eligibilityreview",
                    ),
                ),
            ],
            options={
                "ordering": ["opened_at", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("automated", True), ("state__in", ["open", "addressed"])
                        ),
                        fields=("review", "code"),
                        name="one_live_automated_finding_per_code",
                    )
                ],
            },
        ),
    ]
