# Generated by Django 5.2.17 on 2026-09-26 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FixtureJudge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="FixtureProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("summary", models.TextField(blank=True)),
                ("repo_url", models.URLField(max_length=500)),
                ("submitted_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="FixtureTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="FixtureTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ImportedFixture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_path", models.CharField(max_length=500)),
                ("event_external_id", models.CharField(max_length=64)),
                ("event_name", models.CharField(max_length=200)),
                ("event_submissions_close", models.DateTimeField()),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FixtureScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="integrations.fixturejudge",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="integrations.fixtureproject",
                    ),
                ),
                (
                    "fixture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="integrations.importedfixture",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fixtureproject",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="integrations.fixtureteam",
            ),
        ),
        migrations.CreateModel(
            name="FixtureTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="integrations.fixtureteam",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fixtureproject",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="integrations.fixturetrack",
            ),
        ),
        migrations.AddField(
            model_name="fixturejudge",
            name="tracks",
            field=models.ManyToManyField(related_name="judges", to="integrations.fixturetrack"),
        ),
        migrations.AddField(
            model_name="fixturetrack",
            name="fixture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="integrations.importedfixture",
            ),
        ),
        migrations.AddField(
            model_name="fixtureteam",
            name="fixture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="integrations.importedfixture",
            ),
        ),
        migrations.AddField(
            model_name="fixtureproject",
            name="fixture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="integrations.importedfixture",
            ),
        ),
        migrations.AddField(
            model_name="fixturejudge",
            name="fixture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="judges",
                to="integrations.importedfixture",
            ),
        ),
        migrations.CreateModel(
            name="FixtureScoreCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("value", models.IntegerField()),
                (
                    "score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="integrations.fixturescore",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("score", "name"), name="unique_criterion_per_score"
                    )
                ],
            },
        ),
    ]
