# Generated by Django 5.2.17 on 2026-09-27 07:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0003_webhooksubscription_webhookdelivery"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("source_event_name", models.CharField(blank=True, max_length=200)),
                ("sections", models.JSONField(default=list)),
                ("archive", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_templates",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "name"), name="unique_event_template_name"
                    )
                ],
            },
        ),
    ]
