# Generated by Django 5.2.17 on 2026-09-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0005_externalqualifierimport_externalqualifierbinding"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhooksubscription",
            name="platform",
            field=models.CharField(
                choices=[
                    ("generic", "Generic (signed Conflux envelope)"),
                    ("discord", "Discord incoming webhook"),
                    ("slack", "Slack incoming webhook"),
                ],
                default="generic",
                max_length=10,
            ),
        ),
    ]
