# Generated by Django 5.2.17 on 2026-09-28 03:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0006_webhooksubscription_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("destination", models.URLField(max_length=2048)),
                ("body", models.TextField()),
                ("headers", models.JSONField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("status_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=200)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="integrations.webhookdelivery",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
