# Generated by Django 5.2.17 on 2026-09-28 05:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_announcement_hidden_at_announcement_version"),
        ("integrations", "0007_webhookattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveRestoration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("source_sha256", models.CharField(max_length=64)),
                ("source_archive", models.JSONField()),
                ("identity_map", models.JSONField()),
                ("restored_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_restoration",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
