# Generated by Django 5.2.17 on 2026-09-28 06:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0009_retention_controls"),
        ("workspaces", "0002_alter_membership_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("scenario", models.CharField(max_length=40)),
                ("seed", models.PositiveIntegerField()),
                ("participants", models.PositiveSmallIntegerField()),
                ("judges", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demo_scenario",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
