# Generated by Django 5.2.17 on 2026-09-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="governancesettings",
            name="read_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="governancesettings",
            name="read_only_message",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
