# Generated by Django 5.2.17 on 2026-09-28 06:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0005_announcement_hidden_at_announcement_version"),
        ("projects", "0004_mentornote"),
        ("workspaces", "0002_alter_membership_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("key", models.SlugField()),
                ("name", models.CharField(max_length=80)),
                (
                    "applies_to",
                    models.CharField(
                        choices=[("project", "Project"), ("person", "Person"), ("event", "Event")],
                        max_length=10,
                    ),
                ),
                ("allows_multiple", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxonomies",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="TaxonomyTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("key", models.SlugField()),
                ("label", models.CharField(max_length=80)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "taxonomy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="taxonomy.taxonomy",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "key"],
            },
        ),
        migrations.CreateModel(
            name="TaxonomyAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[("project", "Project"), ("person", "Person"), ("event", "Event")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxonomy_assignments",
                        to="events.event",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxonomy_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxonomy_assignments",
                        to="projects.project",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="taxonomy.taxonomyterm",
                    ),
                ),
            ],
            options={
                "ordering": ["term__taxonomy__key", "term__position", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="taxonomy",
            constraint=models.UniqueConstraint(
                fields=("workspace", "key"), name="unique_taxonomy_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="taxonomyterm",
            constraint=models.UniqueConstraint(
                fields=("taxonomy", "key"), name="unique_taxonomy_term_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="taxonomyassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("person__isnull", True),
                        ("project__isnull", False),
                        ("subject_type", "project"),
                    ),
                    models.Q(
                        ("person__isnull", False),
                        ("project__isnull", True),
                        ("subject_type", "person"),
                    ),
                    models.Q(
                        ("person__isnull", True),
                        ("project__isnull", True),
                        ("subject_type", "event"),
                    ),
                    _connector="OR",
                ),
                name="taxonomy_assignment_subject_matches_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxonomyassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", False)),
                fields=("term", "project"),
                name="unique_taxonomy_project_term",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxonomyassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("person__isnull", False)),
                fields=("term", "event", "person"),
                name="unique_taxonomy_person_term",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxonomyassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subject_type", "event")),
                fields=("term", "event"),
                name="unique_taxonomy_event_term",
            ),
        ),
    ]
