# Generated by Django 5.2.17 on 2026-09-27 00:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifactUploadIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("object_key", models.CharField(max_length=500)),
                ("expected_size", models.PositiveBigIntegerField()),
                ("expected_type", models.CharField(max_length=200)),
                ("upload_id", models.CharField(blank=True, max_length=300)),
                ("part_count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_intents",
                        to="artifacts.artifact",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
