# Generated by Django 5.2.17 on 2026-09-27 00:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0002_artifactuploadintent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifactValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("validator", models.CharField(max_length=80)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("warning", "Warning"),
                            ("blocked", "Blocked"),
                            ("retry", "Retry"),
                        ],
                        max_length=12,
                    ),
                ),
                ("detail", models.CharField(max_length=500)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validations",
                        to="artifacts.artifact",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_at", "-id"],
            },
        ),
    ]
