# Generated by Django 5.2.17 on 2026-09-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0003_artifactvalidation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending upload"),
                    ("uploaded", "Uploaded"),
                    ("ready", "Ready"),
                    ("rejected", "Rejected"),
                    ("purged", "Purged by retention policy"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
