# Generated by Django 5.2.17 on 2026-09-28 07:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0004_retention_controls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifactInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("clean", "Clean"),
                            ("warnings", "Warnings"),
                            ("blocked", "Blocked"),
                        ],
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(default="content", max_length=10)),
                ("detected_type", models.CharField(blank=True, max_length=40)),
                ("findings", models.JSONField(default=list)),
                ("facts", models.JSONField(default=dict)),
                ("preview", models.TextField(blank=True)),
                ("inspector_version", models.CharField(max_length=10)),
                ("inspected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="artifacts.artifact",
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-inspected_at", "-id"],
            },
        ),
    ]
