# Generated by Django 5.2.17 on 2026-09-27 01:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0002_submission_submissionversion_and_more"),
        ("stages", "0002_stage_participation_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "candidate_type",
                    models.CharField(
                        choices=[("project", "Project")], default="project", max_length=20
                    ),
                ),
                (
                    "pool_strategy",
                    models.CharField(
                        choices=[
                            ("all_judges", "All judges score every candidate"),
                            ("assigned_subset", "Judges score an assigned subset"),
                        ],
                        default="all_judges",
                        max_length=20,
                    ),
                ),
                ("results_visible_to_participants", models.BooleanField(default=False)),
                ("draft_criteria", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_plans",
                        to="stages.stage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RubricVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("criteria", models.JSONField()),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rubric_versions",
                        to="evaluations.evaluationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Ballot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ballots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ballots",
                        to="projects.project",
                    ),
                ),
                (
                    "rubric_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ballots",
                        to="evaluations.rubricversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BallotResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("criterion_id", models.CharField(max_length=64)),
                ("score", models.FloatField()),
                (
                    "ballot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="evaluations.ballot",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ballot", "criterion_id"), name="unique_ballot_response"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="evaluationplan",
            constraint=models.UniqueConstraint(
                fields=("stage", "name"), name="unique_evaluation_plan_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="rubricversion",
            constraint=models.UniqueConstraint(
                fields=("plan", "number"), name="unique_rubric_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="ballot",
            constraint=models.UniqueConstraint(
                fields=("rubric_version", "judge", "project"), name="unique_ballot"
            ),
        ),
    ]
