# Generated by Django 5.2.17 on 2026-09-27 02:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0001_initial"),
        ("events", "0001_initial"),
        ("projects", "0002_submission_submissionversion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("coverage", models.PositiveIntegerField()),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignment_versions",
                        to="evaluations.evaluationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="projects.project",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="evaluations.assignmentversion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evaluationplan",
            name="active_assignment_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="evaluations.assignmentversion",
            ),
        ),
        migrations.CreateModel(
            name="ConflictOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "declared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conflicts_declared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts_of_interest",
                        to="events.event",
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declared_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge_conflicts",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvaluationPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_pools",
                        to="events.event",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evaluationplan",
            name="pool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plans",
                to="evaluations.evaluationpool",
            ),
        ),
        migrations.CreateModel(
            name="PoolMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="evaluations.evaluationpool",
                    ),
                ),
                (
                    "track_expertise",
                    models.ManyToManyField(
                        blank=True, related_name="expert_judges", to="events.track"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="assignmentversion",
            constraint=models.UniqueConstraint(
                fields=("plan", "number"), name="unique_assignment_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                fields=("version", "judge", "project"), name="unique_assignment"
            ),
        ),
        migrations.AddConstraint(
            model_name="conflictofinterest",
            constraint=models.UniqueConstraint(
                fields=("judge", "project"), name="unique_conflict_of_interest"
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationpool",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="unique_evaluation_pool_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="poolmembership",
            constraint=models.UniqueConstraint(
                fields=("pool", "judge"), name="unique_pool_membership"
            ),
        ),
    ]
