# Generated by Django 5.2.17 on 2026-09-27 02:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0002_assignmentversion_assignment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NormalizationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("ridge_lambda", models.FloatField()),
                ("iterations", models.PositiveIntegerField()),
                ("converged", models.BooleanField()),
                ("grand_mean", models.FloatField()),
                ("evidence", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="normalization_runs",
                        to="evaluations.evaluationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan", "number"), name="unique_normalization_run"
                    )
                ],
            },
        ),
    ]
