# Generated by Django 5.2.17 on 2026-09-27 11:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0004_evaluationplan_published_normalization_run_and_more"),
        ("projects", "0003_project_track"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationplan",
            name="mode",
            field=models.CharField(
                choices=[
                    ("rubric", "Weighted rubric scoring"),
                    ("pairwise", "Head-to-head pairwise comparison"),
                ],
                default="rubric",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PairwiseRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("prior_games", models.FloatField()),
                ("iterations", models.PositiveIntegerField()),
                ("converged", models.BooleanField()),
                ("evidence", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pairwise_runs",
                        to="evaluations.evaluationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.AddField(
            model_name="evaluationplan",
            name="published_pairwise_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="evaluations.pairwiserun",
            ),
        ),
        migrations.CreateModel(
            name="PairwiseComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pairwise_comparisons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairwise_comparisons",
                        to="evaluations.evaluationplan",
                    ),
                ),
                (
                    "project_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pairwise_as_a",
                        to="projects.project",
                    ),
                ),
                (
                    "project_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pairwise_as_b",
                        to="projects.project",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pairwise_wins",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan", "judge", "project_a", "project_b"),
                        name="unique_pairwise_comparison",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("project_a__lt", models.F("project_b"))),
                        name="pairwise_comparison_canonical_order",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pairwiserun",
            constraint=models.UniqueConstraint(
                fields=("plan", "number"), name="unique_pairwise_run"
            ),
        ),
    ]
