# Generated by Django 5.2.17 on 2026-09-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0005_evaluationplan_mode_pairwiserun_and_more"),
        ("projects", "0003_project_track"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballot",
            name="is_calibration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evaluationplan",
            name="calibration_projects",
            field=models.ManyToManyField(
                blank=True, related_name="calibration_plans", to="projects.project"
            ),
        ),
        migrations.AddField(
            model_name="evaluationplan",
            name="calibration_required",
            field=models.BooleanField(default=False),
        ),
    ]
