# Generated by Django 5.2.17 on 2026-09-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0006_ballot_is_calibration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationplan",
            name="blind_judging",
            field=models.BooleanField(default=False),
        ),
    ]
