# Generated by Django 5.2.17 on 2026-09-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0007_evaluationplan_blind_judging"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationplan",
            name="prize_judging",
            field=models.BooleanField(default=False),
        ),
    ]
