# Generated by Django 5.2.17 on 2026-09-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0008_evaluationplan_prize_judging"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationplan",
            name="feedback_anonymous",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="evaluationplan",
            name="feedback_visible_to_participants",
            field=models.BooleanField(default=False),
        ),
    ]
