# Generated by Django 5.2.17 on 2026-09-27 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0009_evaluationplan_feedback_anonymous_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationplan",
            name="hybrid_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hybrid_tiebreaks",
                to="evaluations.evaluationplan",
            ),
        ),
    ]
