# Generated by Django 5.2.17 on 2026-09-27 20:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0010_evaluationplan_hybrid_source"),
        ("events", "0001_initial"),
        ("participation", "0003_teamopening_marketplaceprofile"),
        ("projects", "0003_project_track"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="COIRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("team_membership", "Shared team"),
                            ("project_membership", "Project member"),
                            ("project_creator", "Project creator"),
                        ],
                        max_length=20,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("event", "kind"), name="unique_coi_rule")
                ],
            },
        ),
        migrations.CreateModel(
            name="JudgeCOIRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("team", "Team"),
                            ("institution", "Institution"),
                            ("domain", "Domain"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "declared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coi_relationships_declared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="participation.team",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "team")),
                        fields=("event", "judge", "team"),
                        name="unique_judge_team_coi",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind__in", ["institution", "domain"])),
                        fields=("event", "judge", "kind", "value"),
                        name="unique_judge_value_coi",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectCOIAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("team", "Team"),
                            ("institution", "Institution"),
                            ("domain", "Domain"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projects.project"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "kind", "value"), name="unique_project_coi_attribute"
                    )
                ],
            },
        ),
    ]
